spring.application.name=user-service
server.port=9020

jwt.secretKey=aunteuntenthsnthstnhsthscdighdthuthdtdihtid

spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
